spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_phoneshope
    username: phoneshope
    password: phoneshope123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Options: update, create, create-drop, validate, none
    show-sql: true
